import { useEffect, useState } from 'react';
import { api } from '../api'; import PageHeader from '../components/PageHeader'; import Modal from '../components/Modal';
const empty = { patient: '', clinician: '', scheduledAt: '', type: 'video', reason: '' };
export default function Appointments() {
  const [items, setItems] = useState([]); const [patients, setPatients] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = () => api('/appointments').then(setItems).catch(e => setError(e.message));
  useEffect(() => { load(); api('/patients').then(setPatients).catch(e => setError(e.message)); }, []);
  const save = async e => { e.preventDefault(); try { await api('/appointments', { method: 'POST', body: JSON.stringify({ ...form, scheduledAt: new Date(form.scheduledAt).toISOString() }) }); setOpen(false); setForm(empty); load(); } catch (err) { setError(err.message); } };
  return <><PageHeader title="Appointments" description="Plan and track patient visits." action={<button className="primary" onClick={() => setOpen(true)}>+ Schedule visit</button>} />{error && <div className="error">{error}</div>}<div className="card table-wrap"><table><thead><tr><th>Patient</th><th>Clinician</th><th>When</th><th>Type</th><th>Status</th></tr></thead><tbody>{items.map(a => <tr key={a._id}><td><b>{a.patient?.name || 'Unknown'}</b><small>{a.reason || 'Consultation'}</small></td><td>{a.clinician}</td><td>{new Date(a.scheduledAt).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</td><td className="capitalize">{a.type}</td><td><span className={`badge ${a.status}`}>{a.status}</span></td></tr>)}</tbody></table>{!items.length && <p className="empty">No appointments found.</p>}</div>{open && <Modal title="Schedule visit" onClose={() => setOpen(false)}><form onSubmit={save} className="form-grid"><label className="wide">Patient<select required value={form.patient} onChange={e => setForm({ ...form, patient: e.target.value })}><option value="">Select patient…</option>{patients.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></label><label>Clinician<input required value={form.clinician} onChange={e => setForm({ ...form, clinician: e.target.value })} /></label><label>Date & time<input required type="datetime-local" value={form.scheduledAt} onChange={e => setForm({ ...form, scheduledAt: e.target.value })} /></label><label>Visit type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="video">Video</option><option value="phone">Phone</option><option value="in-person">In person</option></select></label><label className="wide">Reason<input value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></label><button className="primary wide">Schedule</button></form></Modal>}</>;
}
