import { useEffect, useState } from 'react';
import { api } from '../api'; import PageHeader from '../components/PageHeader'; import Modal from '../components/Modal';
const empty = { name: '', dateOfBirth: '', phone: '', email: '', address: '', emergencyContact: '', notes: '' };
export default function Patients() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const load = () => api(`/patients${search ? `?search=${encodeURIComponent(search)}` : ''}`).then(setItems).catch(e => setError(e.message));
  useEffect(() => {
    load();
  }, [search]);
  const save = async e => { e.preventDefault(); try { await api('/patients', { method: 'POST', body: JSON.stringify(form) }); setForm(empty); setOpen(false); load(); } catch (err) { setError(err.message); } };
  return <><PageHeader title="Patients" description="Securely manage the people in your care." action={<button className="primary" onClick={() => setOpen(true)}>+ Add patient</button>} />{error && <div className="error">{error}</div>}<div className="toolbar"><input placeholder="Search by name, email or phone…" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="card table-wrap"><table><thead><tr><th>Patient</th><th>Date of birth</th><th>Contact</th><th>Added</th></tr></thead><tbody>{items.map(p => <tr key={p._id}><td><b>{p.name}</b></td><td>{new Date(p.dateOfBirth).toLocaleDateString()}</td><td>{p.email || p.phone || '—'}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!items.length && <p className="empty">No patients found.</p>}</div>{open && <Modal title="Add patient" onClose={() => setOpen(false)}><form onSubmit={save} className="form-grid"><label className="wide">Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Date of birth<input required type="date" value={form.dateOfBirth} onChange={e => setForm({ ...form, dateOfBirth: e.target.value })} /></label><label>Phone<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label className="wide">Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label className="wide">Address<input value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></label><label className="wide">Notes<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><button className="primary wide">Save patient</button></form></Modal>}</>;
}
