import { useEffect, useState } from 'react';
import { api } from '../api'; import PageHeader from '../components/PageHeader'; import Modal from '../components/Modal';
const empty = { patient: '', clinician: '', diagnosis: '', treatment: '', notes: '' };
export default function Records() {
  const [items, setItems] = useState([]); const [patients, setPatients] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = () => api('/records').then(setItems).catch(e => setError(e.message));
  useEffect(() => { load(); api('/patients').then(setPatients).catch(e => setError(e.message)); }, []);
  const save = async e => { e.preventDefault(); try { await api('/records', { method: 'POST', body: JSON.stringify(form) }); setOpen(false); setForm(empty); load(); } catch (err) { setError(err.message); } };
  return <><PageHeader title="Medical records" description="Document diagnoses and treatment securely." action={<button className="primary" onClick={() => setOpen(true)}>+ New record</button>} />{error && <div className="error">{error}</div>}<div className="record-grid">{items.map(r => <article className="card record" key={r._id}><div className="record-top"><span className="badge">{new Date(r.recordedAt).toLocaleDateString()}</span><b>{r.patient?.name || 'Unknown patient'}</b></div><h3>{r.diagnosis}</h3><p>{r.notes || 'No additional notes.'}</p><div className="muted">Treatment: {r.treatment || 'Not specified'} · {r.clinician}</div></article>)}{!items.length && <div className="card empty">No medical records found.</div>}</div>{open && <Modal title="New medical record" onClose={() => setOpen(false)}><form onSubmit={save} className="form-grid"><label className="wide">Patient<select required value={form.patient} onChange={e => setForm({ ...form, patient: e.target.value })}><option value="">Select patient…</option>{patients.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></label><label>Clinician<input required value={form.clinician} onChange={e => setForm({ ...form, clinician: e.target.value })} /></label><label>Diagnosis<input required value={form.diagnosis} onChange={e => setForm({ ...form, diagnosis: e.target.value })} /></label><label className="wide">Treatment<input value={form.treatment} onChange={e => setForm({ ...form, treatment: e.target.value })} /></label><label className="wide">Notes<textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><button className="primary wide">Save record</button></form></Modal>}</>;
}
